
server:
  port: ${PORT:9004}
  

spring:
  jpa:
    generate-ddl: true
    database: mysql
    show-sql: true
    hibernate:
     ddl-auto: update 
  datasource:
    platform: mysql
    url: jdbc:mysql://10.145.81.119:3306/inspiratti?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: inspiratti
    password: root@123
  application:
    name: report-abuse-service
    
  jackson:
    serialization:
      fail-on-empty-beans: false


  #contextPath: /resource
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8000/user
  


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      
